'use client';

import React, { useState, useMemo } from 'react';
import { useStore } from '@/store';
import { IndianRupee, FileDown, Plus, X, Receipt } from 'lucide-react';
import { Invoice } from '@/types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function BillingPage() {
  const { patients, appointments, invoices, addInvoice, updateInvoice } = useStore();
  const [invoiceModal, setInvoiceModal] = useState(false);
  const [selectedApptId, setSelectedApptId] = useState('');
  const [discount, setDiscount] = useState(0);
  const [tax, setTax] = useState(18);

  const billableAppointments = useMemo(() => 
    appointments.filter(a => a.status === 'Completed' && !invoices.some(i => i.appointmentId === a.id)),
    [appointments, invoices]
  );

  const selectedAppt = appointments.find(a => a.id === selectedApptId);
  const treatmentCost = selectedAppt?.treatments.reduce((acc, t) => acc + t.cost, 0) || 0;
  const discountAmount = treatmentCost * discount / 100;
  const taxAmount = (treatmentCost - discountAmount) * tax / 100;
  const finalAmount = treatmentCost - discountAmount + taxAmount;

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedAppt) return;
    // eslint-disable-next-line react-hooks/purity
    const currentId = 'inv' + Date.now();
    addInvoice({
      id: currentId,
      appointmentId: selectedAppt.id,
      patientId: selectedAppt.patientId,
      treatmentCost,
      discount,
      tax,
      finalAmount,
      status: 'Pending',
      date: new Date().toISOString().split('T')[0],
    });
    setInvoiceModal(false);
    setSelectedApptId('');
    setDiscount(0);
    setTax(18);
  };

  const handleDownloadPDF = (inv: Invoice) => {
    const patient = patients.find(p => p.id === inv.patientId);
    const appt = appointments.find(a => a.id === inv.appointmentId);
    
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(14, 165, 233); // Primary theme color
    doc.text('SmileSync', 14, 22);
    doc.setFontSize(14);
    doc.setTextColor(100, 116, 139);
    doc.text('INVOICE', 14, 30);
    
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    doc.text(`Invoice #: ${inv.id.slice(-6).toUpperCase()}`, 150, 22);
    doc.text(`Date: ${inv.date}`, 150, 28);
    doc.text(`Status: ${inv.status.toUpperCase()}`, 150, 34);

    doc.setFontSize(11);
    doc.text('Bill To:', 14, 45);
    doc.setFontSize(10);
    doc.text(`Patient: ${patient?.name || 'Unknown'}`, 14, 52);
    if (patient?.phone) doc.text(`Phone: ${patient.phone}`, 14, 58);
    if (appt?.date) doc.text(`Treatment Date: ${appt.date}`, 14, 64);

    const tableData = appt?.treatments.map(t => [
      `Tooth #${t.toothNumber} - ${t.notes}`, 
      `₹ ${t.cost.toLocaleString()}`
    ]) || [['Treatments', `₹ ${inv.treatmentCost.toLocaleString()}`]];

    tableData.push(['Subtotal', `₹ ${inv.treatmentCost.toLocaleString()}`]);
    
    if (inv.discount > 0) {
      const discountAmount = (inv.treatmentCost * inv.discount) / 100;
      tableData.push([`Discount (${inv.discount}%)`, `- ₹ ${discountAmount.toFixed(2)}`]);
    }
    
    if (inv.tax > 0) {
      const taxableAmount = inv.treatmentCost - ((inv.treatmentCost * inv.discount) / 100);
      const taxAmount = (taxableAmount * inv.tax) / 100;
      tableData.push([`Tax (${inv.tax}%)`, `+ ₹ ${taxAmount.toFixed(2)}`]);
    }
    
    autoTable(doc, {
      startY: 75,
      head: [['Description', 'Amount']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [14, 165, 233], textColor: [255, 255, 255] },
      styles: { fontSize: 10, cellPadding: 6 },
      columnStyles: { 1: { halign: 'right' } }
    });

    const finalY = (doc as any).lastAutoTable.finalY || 80;
    
    // Total Amount highlight box
    doc.setFillColor(241, 245, 249);
    doc.rect(120, finalY + 8, 76, 16, 'F');
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.text('Total:', 125, finalY + 19);
    doc.setTextColor(14, 165, 233);
    doc.text(`₹ ${inv.finalAmount.toLocaleString()}`, 190, finalY + 19, { align: 'right' });
    
    // Footer
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by SmileSync - Owner Edition', 105, 280, { align: 'center' });

    doc.save(`SmileSync_Invoice_${inv.id.slice(-6)}.pdf`);
  };

  // Summary stats
  const totalRevenue = invoices.filter(i => i.status === 'Paid').reduce((a, i) => a + i.finalAmount, 0);
  const totalPending = invoices.filter(i => i.status === 'Pending').reduce((a, i) => a + i.finalAmount, 0);

  return (
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Billing & Invoices</h1>
          <p className="page-subtitle">{invoices.length} invoices generated</p>
        </div>
        <button className="btn btn-primary" onClick={() => setInvoiceModal(true)}>
          <Plus size={18} /> Generate Invoice
        </button>
      </div>

      {/* Revenue Cards */}
      <div className="grid grid-3 gap-5" style={{ marginBottom: '1.75rem' }}>
        <div className="card stat-card">
          <div className="stat-icon" style={{ background: 'rgba(16, 185, 129, 0.12)', color: 'var(--success)' }}>
            <IndianRupee size={26} />
          </div>
          <div>
            <p className="stat-label">Total Revenue</p>
            <h3 className="stat-value">₹{totalRevenue.toLocaleString()}</h3>
          </div>
        </div>
        <div className="card stat-card">
          <div className="stat-icon" style={{ background: 'rgba(245, 158, 11, 0.12)', color: 'var(--warning)' }}>
            <Receipt size={26} />
          </div>
          <div>
            <p className="stat-label">Pending Amount</p>
            <h3 className="stat-value">₹{totalPending.toLocaleString()}</h3>
          </div>
        </div>
        <div className="card stat-card">
          <div className="stat-icon" style={{ background: 'var(--info-bg)', color: 'var(--primary)' }}>
            <FileDown size={26} />
          </div>
          <div>
            <p className="stat-label">Total Invoices</p>
            <h3 className="stat-value">{invoices.length}</h3>
          </div>
        </div>
      </div>

      {/* Invoices Table */}
      <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
        <div className="table-wrapper" style={{ border: 'none', borderRadius: 0 }}>
          <table>
            <thead>
              <tr>
                <th>Invoice ID</th>
                <th>Date</th>
                <th>Patient</th>
                <th>Treatment Cost</th>
                <th>Discount</th>
                <th>Tax</th>
                <th>Total</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {invoices.length === 0 ? (
                <tr><td colSpan={9} className="empty-state">No invoices generated yet. Complete an appointment and generate your first invoice.</td></tr>
              ) : (
                [...invoices].sort((a, b) => b.date.localeCompare(a.date)).map(inv => {
                  const patient = patients.find(p => p.id === inv.patientId);
                  return (
                    <tr key={inv.id}>
                      <td style={{ fontWeight: 600 }}>#{inv.id.slice(-6)}</td>
                      <td>{inv.date}</td>
                      <td>{patient?.name || 'Unknown'}</td>
                      <td>₹{inv.treatmentCost.toLocaleString()}</td>
                      <td>{inv.discount}%</td>
                      <td>{inv.tax}%</td>
                      <td style={{ fontWeight: 700 }}>₹{inv.finalAmount.toLocaleString()}</td>
                      <td>
                        <select
                          className="status-select"
                          style={{
                            background: inv.status === 'Paid' ? 'var(--success-bg)' : 'var(--warning-bg)',
                            color: inv.status === 'Paid' ? 'var(--success)' : 'var(--warning)',
                          }}
                          value={inv.status}
                          onChange={e => updateInvoice(inv.id, { status: e.target.value as Invoice['status'] })}
                        >
                          <option value="Paid">Paid</option>
                          <option value="Pending">Pending</option>
                        </select>
                      </td>
                      <td>
                        <button className="btn btn-sm" onClick={() => handleDownloadPDF(inv)}>
                          <FileDown size={14} /> PDF
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Generate Invoice Modal */}
      {invoiceModal && (
        <div className="modal-overlay" onClick={() => setInvoiceModal(false)}>
          <div className="modal-content" style={{ width: '520px' }} onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h2 className="modal-title"><IndianRupee size={22} color="var(--primary)" /> Generate Invoice</h2>
              <button className="btn btn-icon" onClick={() => { setInvoiceModal(false); setSelectedApptId(''); }}><X size={20} /></button>
            </div>
            <form onSubmit={handleGenerate}>
              <div className="form-group">
                <label className="form-label">Select Completed Appointment</label>
                <select required className="form-select" value={selectedApptId} onChange={e => setSelectedApptId(e.target.value)}>
                  <option value="">Choose an appointment...</option>
                  {billableAppointments.map(a => {
                    const patient = patients.find(p => p.id === a.patientId);
                    return <option key={a.id} value={a.id}>{a.date} — {patient?.name} ({a.treatmentType})</option>;
                  })}
                </select>
              </div>

              {selectedAppt && (
                <>
                  <div className="invoice-summary" style={{ margin: '1.25rem 0' }}>
                    <div className="invoice-row">
                      <span style={{ color: 'var(--text-muted)' }}>Treatments ({selectedAppt.treatments.length})</span>
                      <strong>₹{treatmentCost.toLocaleString()}</strong>
                    </div>

                    <div className="grid grid-2 gap-4" style={{ margin: '1rem 0' }}>
                      <div className="form-group" style={{ margin: 0 }}>
                        <label className="form-label">Discount (%)</label>
                        <input type="number" min="0" max="100" className="form-input" value={discount} onChange={e => setDiscount(Number(e.target.value))} />
                      </div>
                      <div className="form-group" style={{ margin: 0 }}>
                        <label className="form-label">Tax (%)</label>
                        <input type="number" min="0" className="form-input" value={tax} onChange={e => setTax(Number(e.target.value))} />
                      </div>
                    </div>

                    {discount > 0 && (
                      <div className="invoice-row">
                        <span style={{ color: 'var(--text-muted)' }}>Discount ({discount}%)</span>
                        <span style={{ color: 'var(--success)' }}>-₹{discountAmount.toFixed(2)}</span>
                      </div>
                    )}
                    <div className="invoice-row">
                      <span style={{ color: 'var(--text-muted)' }}>Tax ({tax}%)</span>
                      <span>+₹{taxAmount.toFixed(2)}</span>
                    </div>

                    <hr className="invoice-divider" />
                    <div className="invoice-row">
                      <span className="invoice-total">Final Amount</span>
                      <span className="invoice-amount">₹{finalAmount.toFixed(2)}</span>
                    </div>
                  </div>

                  <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.75rem' }}>
                    <button type="button" className="btn" onClick={() => { setInvoiceModal(false); setSelectedApptId(''); }}>Cancel</button>
                    <button type="submit" className="btn btn-primary">Create Invoice</button>
                  </div>
                </>
              )}

              {!selectedAppt && billableAppointments.length === 0 && (
                <div className="empty-state" style={{ padding: '1.5rem' }}>
                  No completed appointments available for billing. Mark appointments as &quot;Completed&quot; first.
                </div>
              )}
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
